config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :machineries
  resources :tractors
  resources :items
  resources :customers
  resources :invoices
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: :registrations, sessions: :sessions, confirmations: 'confirmations'
                                  },
                     path: 'user'

  resource :user do
    resources :openids
  end

  # Admin
  namespace :admin do
    resources :users do
      member do
        patch :confirm
      end
    end
  end
  #-- End of Admin
  get 'creatives/index'
  get 'contact' => 'home#contact'
  post 'contact' => 'home#contact'
  get 'recommend' => 'home#recommend'
  post 'recommend' => 'home#recommend'

  root to: 'home#index', via: [:get]

  match "/404", :to => "errors#error", via: :all
  match "/500", :to => "errors#error", via: :all
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  enum cat: { customer:0, provider:1 }, _prefix: :cat
  has_many :invoices
  has_many :tractors
  has_many :machineries
  has_many :items
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    if params[:cat]
      @customers = Customer.where(:cat => params[:cat])
    else
      @customers = Customer.all
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:cat, :surname, :name, :fathername, :telephone, :cellphone, :dob, :email, :city, :address, :activity)
    end
end

app/views/customers/_form.html.haml
= semantic_form_for @customer do |f|
  = f.inputs do
    = f.input :cat, label: 'Κατηγορία', input_html: { autofocus: true }
    = f.input :surname, label: 'Επώνυμο'
    = f.input :name, label: 'Όνομα'
    = f.input :fathername, label: 'Πατρώνυμο'
    = f.input :telephone, label: 'Τηλέφωνο'
    = f.input :cellphone, label: 'Κινητό'
    = f.input :dob, label: 'Ημερ. Γεν.'
    = f.input :email, label: 'Email'
    = f.input :city, label: 'Πόλη'
    = f.input :address, label: 'Διεύθυση'
    = f.input :activity, label: 'Δραστηριότητα'

  = f.actions do
    = f.action :submit, :as => :input

app/views/customers/edit.html.haml
%h1 Επεξεργασία Στοιχείων Πελάτη

= render 'form'

= link_to customers_path, class: 'btn btn-success' do
  .fa.fa-plus
  Πίσω

app/views/customers/index.html.haml
.page-header
  %h1
    - if params[:cat]=="0"
      ="Πελάτες"
    - else
      ="Προμηθευτές"
    %div
      = link_to new_customer_path, class: 'btn btn-success' do
        .fa.fa-plus
        Προσθήκη Χρήστη
%table.table.table-bordered
  %thead
    %tr
      %th A/A
      %th Κατηγορία
      %th Επίθετο
      %th Όνομα
      %th ΑΦΜ
      %th Σταθερό τηλέφωνο
      %th Κινητό τηλέφωνο
      %th Email
      %th Πόλη
      %th Δραστηριότητα
      %th{ colspan: '3' } Ενέργειες

  %tbody
    - @customers.each_with_index do |customer, index|
      %tr
        %td
          =index+1
        %td
          - if customer.cat=="customer"
            ="Πελάτης"
          - else
            ="Προμηθευτής"
        %td= link_to customer.surname, customer, style: 'font-weight:bold'
        %td= customer.name
        %th= customer.afm
        %td= customer.telephone
        %td= customer.cellphone
        %td= customer.email
        %td= customer.city
        %td= customer.activity
        %td
          = link_to customer, class: 'btn btn-primary' do
            .fa.fa-info-circle
        %td
          = link_to edit_customer_path(customer), class: 'btn btn-warning' do
            .fa.fa-edit
        %td
          = link_to customers_path(@customer), method: :delete, remote: true, data: { confirm: 'Είστε σίγουρος;' }, class: 'btn btn-danger' do
            .fa.fa-trash
%br

app/views/customers/new.html.haml
%h1 Νέα Καταχώρηση Πελάτη/Προμηθευτή

= render 'form'

= link_to customers_path, class: 'btn btn-default col-md-offset-9' do
  .fa.fa-plus
  Πίσω

app/views/customers/show.html.haml
%p#notice= notice
= link_to edit_customer_path(@customer), class: 'btn btn-primary' do
  .fa.fa-plus
  Επεξεργασία

= link_to customers_path, class: 'btn btn-primary' do
  .fa.fa-plus
  Πίσω
%br
%br
.container.bootstrap.snippet
  .row
    .col-sm-10
      %h3
        =@customer.name
        (
        =@customer.fathername
        )
        =@customer.surname
    -# .col-sm-2
    -#   %a.pull-right{:href => "/users"}
    -#     %img.img-circle.img-responsive{:src => "http://www.gravatar.com/avatar/28fd20ccec6865e2d5f0e1f4446eb7bf?s=100", :title => "profile image"}/
  .row
    .col-sm-3
      / left col
      -# .text-center
      -#   %img.avatar.img-circle.img-thumbnail{:alt => "avatar", :src => "http://ssl.gstatic.com/accounts/ui/avatar_2x.png"}/
      -#   %h6 Upload a different photo...
      -#   %input.text-center.center-block.file-upload{:type => "file"}/
      %br/
      -# .panel.panel-default
      -#   .panel-heading
      -#     Ιστοσελίδα
      -#     %i.fa.fa-link.fa-1x
      -#   .panel-body
      -#     %a{:href => "http://bootnipets.com"} bootnipets.com
      %ul.list-group
        %li.list-group-item.text-muted
          Συνολικά
          %i.fa.fa-dashboard.fa-1x
        %li.list-group-item.text-right
          %span.pull-left
            %strong Τιμολόγια
          =link_to Invoice.where(user_id: @customer.id).count, invoices_path(:user_id => @customer)
        %li.list-group-item.text-right
          %span.pull-left
            %strong Τρακτέρ
          =link_to Tractor.where(user_id: @customer.id).count, tractors_path(:user_id => @customer)
        %li.list-group-item.text-right
          %span.pull-left
            %strong Παρελκόμενα
          =link_to Machinery.where(user_id: @customer.id).count, machineries_path(:user_id => @customer)
        %li.list-group-item.text-right
          %span.pull-left
            %strong Πληρωμές
          =link_to Payment.where(user_id: @customer.id).count, payments_path(:user_id => @customer)
        - if @customer.cat=="provider"
          %li.list-group-item.text-right
            %span.pull-left
              %strong Προϊόντα
            =link_to Item.where(supplier_id: @customer.id).count, items_path(:supplier_id => @customer)
      .panel.panel-default
        .panel-heading Social Media
        .panel-body
          %i.fa.fa-facebook.fa-2x
          %i.fa.fa-github.fa-2x
          %i.fa.fa-twitter.fa-2x
          %i.fa.fa-pinterest.fa-2x
          %i.fa.fa-google-plus.fa-2x
    / /col-3

    .col-sm-9
      %br

      %ul#pills-tab.nav.nav-pills.list-group-item{:role => "tablist"}
        %li.nav-item
          %a#pills-home-tab.nav-link.active{"aria-controls" => "pills-info", "aria-selected" => "true", "data-toggle" => "pill", :href => "#pills-info", :role => "tab"} Στοιχεία
        %li.nav-item
          %a#pills-profile-tab.nav-link{"aria-controls" => "pills-tractor", "aria-selected" => "false", "data-toggle" => "pill", :href => "#pills-tractor", :role => "tab"} Τρακτέρ
        %li.nav-item
          %a#pills-contact-tab.nav-link{"aria-controls" => "pills-payment", "aria-selected" => "false", "data-toggle" => "pill", :href => "#pills-payment", :role => "tab"} Πληρωμές
      #pills-tabContent.tab-content.list-group-item
        #pills-info.tab-pane.fade.show.active{"aria-labelledby" => "pills-info-tab", :role => "tabpanel"}
          %br
          %table.table.table-bordered
            %thead
              %br
                .col-md-2
                  ΑΦΜ:
                .col-md-3
                  =@customer.afm
              %br
                .col-md-2
                  Ημ. Γεν.:
                .col-md-3
                  =@customer.dob
              %br
                .col-md-2
                  Τηλέφωνο:
                .col-md-3
                  =@customer.telephone
              %br
                .col-md-2
                  Κινητό:
                .col-md-3
                  =@customer.cellphone
        #pills-tractor.tab-pane.fade{"aria-labelledby" => "pills-tractor-tab", :role => "tabpanel"}
          %br
          =customer.items.count
        #pills-payment.tab-pane.fade{"aria-labelledby" => "pills-payment-tab", :role => "tabpanel"} ...