config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :machineries
  resources :tractors
  resources :items
  resources :customers
  resources :invoices
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: :registrations, sessions: :sessions, confirmations: 'confirmations'
                                  },
                     path: 'user'

  resource :user do
    resources :openids
  end

  # Admin
  namespace :admin do
    resources :users do
      member do
        patch :confirm
      end
    end
  end
  #-- End of Admin
  get 'creatives/index'
  get 'contact' => 'home#contact'
  post 'contact' => 'home#contact'
  get 'recommend' => 'home#recommend'
  post 'recommend' => 'home#recommend'

  root to: 'home#index', via: [:get]

  match "/404", :to => "errors#error", via: :all
  match "/500", :to => "errors#error", via: :all
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :owner,
  class_name: 'Customer'
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    if params[:user_id]
      @payments = Payment.where(:user_id => params[:user_id])
    else
      @payments = Payment.all
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:amount, :date, :user_id, :description)
    end
end

app/views/payments/_form.html.haml
= semantic_form_for @payment do |f|
  = f.inputs do

    = f.input :amount, label: 'Ποσό', input_html: { autofocus: true }

    = f.input :date, label: 'Ημερομηνία'

    = f.input :user_id, label: 'Συναλλασόμενος'

    = f.input :description, label: 'Περιγραφή'


  = f.actions do
    = f.action :submit, :as => :input

app/views/payments/edit.html.haml
%h1 Επεξεργασία Πληρωμής

= render 'form'

= link_to 'Στοιχεία', @payment
\|
= link_to 'Πίσω', payments_path

app/views/payments/index.html.haml
.page-header
  %h1
    Πληρωμές
    %div
      = link_to new_payment_path, class: 'btn btn-success' do
        .fa.fa-plus
        Προσθήκη Πληρωμής
%table.table.table-bordered
  %thead
    %tr
      %th A/A
      %th Κωδικός Πληρωμής
      %th Συναλλασόμενος
      %th Ημερομηνία
      %th Ποσό
      %th Περιγραφή
      %th{ colspan: '3' } Ενέργειες

  %tbody
    - @payments.each_with_index do |payment, index|
      %tr
        %td
          =index+1
        %td= payment.id
        %td
          - if payment.user_id
            = link_to payment.user_id.surname, customer_path(payment.user_id)
          - else
            = '--'
        -# %td= link_to invoice.code, invoice, style: 'font-weight:bold'
        %td= payment.date
        %td= payment.ammount
        %td= payment.description
        %td
          = link_to payment, class: 'btn btn-primary' do
            .fa.fa-info-circle
        %td
          = link_to edit_payment_path(payment), class: 'btn btn-warning' do
            .fa.fa-edit
        %td
          = link_to payment_path(@payment), method: :delete, remote: true, data: { confirm: 'Είστε σίγουρος;' }, class: 'btn btn-danger' do
            .fa.fa-trash
%br

app/views/payments/new.html.haml
%h1 Καταχώρηση Νέας Πληρωμής

= render 'form'

= link_to 'Πίσω', payments_path

app/views/payments/show.html.haml
%p#notice= notice

%p
  %b Ποσό:
  = @payment.amount
%p
  %b Ημερομηνία:
  = @payment.date
%p
  %b Συναλλασόμενος:
  = @payment.user_id
%p
  %b Περιγραφή:
  = @payment.description

= link_to 'Επεξεργασία', edit_payment_path(@payment)
= link_to 'Διαγραφή', payments, method: :delete, data: { confirm: 'Είστε Σίγουρος?' }
= link_to 'Πίσω', payments_path