config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :machineries
  resources :tractors
  resources :items
  resources :customers
  resources :invoices
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: :registrations, sessions: :sessions, confirmations: 'confirmations'
                                  },
                     path: 'user'

  resource :user do
    resources :openids
  end

  # Admin
  namespace :admin do
    resources :users do
      member do
        patch :confirm
      end
    end
  end
  #-- End of Admin
  get 'creatives/index'
  get 'contact' => 'home#contact'
  post 'contact' => 'home#contact'
  get 'recommend' => 'home#recommend'
  post 'recommend' => 'home#recommend'

  root to: 'home#index', via: [:get]

  match "/404", :to => "errors#error", via: :all
  match "/500", :to => "errors#error", via: :all
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :supplier,
  class_name: 'Customer'
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    if params[:supplier_id]
      @items = Item.where(:supplier_id => params[:supplier_id])
    else
      @items = Item.all
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:category, :subcategory, :name, :description, :stock, :code, :barcode, :price, :supplier)
    end
end

app/views/items/_form.html.haml
= semantic_form_for @item do |f|
  = f.inputs do
    = f.input :category, label: 'Κατηγορία', input_html: { autofocus: true }
    = f.input :subcategory, label: 'Υποκατηγορία'
    = f.input :name, label: 'Ονομασία'
    = f.input :description, label: 'Περιγραφή'
    = f.input :stock, label: 'Απόθεμα'
    = f.input :code, label: 'Κωδικός'
    = f.input :barcode, label: 'Barcode'
    = f.input :price, label: 'Τιμή'
    = f.input :supplier, label: 'Προμηθευτής'

  = f.actions do
    = f.action :submit, :as => :input

app/views/items/edit.html.haml
%h1 Editing item

= render 'form'

= link_to 'Στοιχεία', @item
\|
= link_to 'Πίσω', items_path

app/views/items/index.html.haml
.page-header
  %h1
    Αποθήκη
    %div
      = link_to new_item_path, class: 'btn btn-success' do
        .fa.fa-plus
        Προσθήκη Προϊόντος
%table.table.table-bordered
  %thead
    %tr
      %th A/A
      %th Κατηγορία
      %th Υποκατηγορία
      %th Ονομασία
      %th Απόθεμα
      %th Κωδικός
      %th Barcode
      %th Τιμή
      %th Προμηθευτής
      %th{ colspan: '3' } Ενέργειες

  %tbody
    - @items.each_with_index do |item, index|
      %tr
        %td
          =index+1
        %td= item.category
        %td= item.subcategory
        %td= link_to item.name, item, style: 'font-weight:bold'
        %td= item.stock
        %td= item.code
        %td= item.barcode
        %td= item.price
        %td
          - if item.supplier_id
            = link_to item.supplier.surname, customer_path(item.supplier)
          - else
            = '--'

        %td
          = link_to item, class: 'btn btn-primary' do
            .fa.fa-info-circle
        %td
          = link_to edit_item_path(item), class: 'btn btn-warning' do
            .fa.fa-edit
        %td
          = link_to items_path(@item), method: :delete, remote: true, data: { confirm: 'Είστε σίγουρος;' }, class: 'btn btn-danger' do
            .fa.fa-trash
%br

app/views/items/new.html.haml
%h1 New item

= render 'form'

= link_to 'Πίσω', items_path

app/views/items/show.html.haml
%p#notice= notice

%p
  %b Κατηγορία:
  = @item.category
%p
  %b Υποκατηγορία:
  = @item.subcategory
%p
  %b Ονομασία:
  = @item.name
%p
  %b Περιγραφή:
  = @item.description
%p
  %b Απόθεμα:
  = @item.stock
%p
  %b Κωδικός:
  = @item.code
%p
  %b Barcode:
  = @item.barcode
%p
  %b Τιμή:
  = @item.price
%p
  %b Προμηθευτής:
  = @item.supplier_id

= link_to 'Επεξεργασία', edit_item_path(@item)
\|
= link_to 'Πίσω', items_path