config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :machineries
  resources :tractors
  resources :items
  resources :customers
  resources :invoices
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: :registrations, sessions: :sessions, confirmations: 'confirmations'
                                  },
                     path: 'user'

  resource :user do
    resources :openids
  end

  # Admin
  namespace :admin do
    resources :users do
      member do
        patch :confirm
      end
    end
  end
  #-- End of Admin
  get 'creatives/index'
  get 'contact' => 'home#contact'
  post 'contact' => 'home#contact'
  get 'recommend' => 'home#recommend'
  post 'recommend' => 'home#recommend'

  root to: 'home#index', via: [:get]

  match "/404", :to => "errors#error", via: :all
  match "/500", :to => "errors#error", via: :all
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google, :facebook]

  has_many :openids, dependent: :destroy

  # Validations always
  validates :email, presence: true
  validates :email, uniqueness: true

  # Validate only on sign_up
  validates :password, length: { minimum: 4, maximum: 128 }, allow_blank: false, if: proc { |u| u.new_record? }

  # Validations for existing users
  validates :current_password, length: { minimum: 4, maximum: 128 }, allow_blank: true

  def name
    "#{first_name} #{last_name}" if first_name.present? || last_name.present?
  end

  def name_formatted
    name.parameterize.underscore
  end

  # Searches for user based on email. Returns found user or new user.
  # ====Returns
  # * +User::ActiveRecord_Relation+ -> user
  def self.find_for_auth(auth, current_user = nil)
    user = current_user

    user = User.where(email: auth.info.email).first_or_initialize if user.nil? # No current user available, user is not already logged in

    if user.new_record?
      user.email = auth.info.email
      user.first_name = auth.info.username
      user.last_name = auth.info.name
      user.password = Devise.friendly_token[0, 20]
    end
    user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  load_and_authorize_resource :user

  def index
    @users = User.all.reorder(created_at: :desc)
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
    if @user.update_attributes(user_params)
      flash[:notice] = 'Successfully updated user ' + @user.email
      redirect_to admin_users_path
    else
      flash[:error] = 'Could not update user ' + @user.email + ' ' + @user.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    redirect_to :back
  end

  def switch_user
    return unless current_user.is_admin?
    sign_in :user, User.find(params[:user_id]), bypass: true
    redirect_to root_url # or user_root_url
  end

  def confirm
    @user.confirmed_at = Time.current
    @user.save(validate: false)
    redirect_to :back
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    skip_before_action :verify_authenticity_token
    skip_authorization_check

    User.omniauth_providers.each do |provider|
      define_method(provider) { handle(provider) }
    end

    private

    def handle(provider)
      auth_hash = request.env['omniauth.auth']
      uid = auth_hash[:uid]
      openid = Openid.find_for_oauth(auth_hash) # Get or create openid
      # If openid exists and is associated with a user, sign in with associated user,
      # even if the email of the associated user and the email of the provided openid are different
      unless (user = openid.user)
        user = User.find_for_auth(auth_hash, current_user) # Get or create users
      end

      begin
        user.skip_confirmation!
        user.save!(validate: false)
        openid.user = user if openid.user != user
        openid.save!

        sign_in user
        flash[:notice] = "User with email #{user.email} successfully added #{provider} provider (#{openid.email})."
        redirect_to after_sign_in_path_for(user) # edit_user_registration_path
      rescue => e
        flash[:error] = e.message
        redirect_to new_user_registration_path
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  # GET /users/1
  # Possibly useless action/code
  def show
    @user = current_user
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User updated successfully'
    else
      flash[:error] = "Couldn't update user: #{@user.errors.full_messages.join('. ')}."
      render :edit
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
end

app/views/admin/users/_form.html.haml
%h1
  - if @user.new_record?
    Create new user
  - else
    Edit User #{@user.email}

= semantic_form_for @user, url: ( @user.new_record? ? admin_users_path : admin_user_path(@user) ) do |f|
  = f.input :first_name, input_html: { autofocus: true }
  = f.input :last_name
  = f.submit 'Save', class: 'btn btn-primary'

app/views/admin/users/edit.html.haml
= render partial: 'form'

app/views/admin/users/index.html.haml
.row
  .col-md-12
    .page-header
      %h1 Users (#{@users.length})
  .col-md-12.table-responsive
    %table.table.table-bordered.table-striped.table-hover.datatable#table-users
      %thead
        %tr
          %th ID
          %th Name
          %th Email
          %th Created At
          %th Last Login
          %th.nowrap Actions
      %tbody
        - @users.each do |user|
          %tr
            %td= link_to user.id, admin_user_path(user), class: 'btn btn-default'
            %td
              = user.name
              %br
              - if user.confirmed?
                %label.btn-xs.btn-success.disabled
                  Confirmed
              - else
                %label.btn-xs.btn-danger.disabled
                  NOT Confirmed
              %br
            %td= user.email
            %td= user.created_at.in_time_zone('Athens')
            %td= user.last_sign_in_at.in_time_zone('Athens') if user.last_sign_in_at
            %td
              .btn-group.flex
                = link_to admin_user_path(user), class: 'btn btn-success' do
                  .fas.fa-user
                = link_to edit_admin_user_path(user), class: 'btn btn-primary' do
                  .fas.fa-edit
                = link_to admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
                  .fas.fa-times

:javascript
  $(document).ready(function() {
    $('#table-users').DataTable( {
      autoWidth: false,
      bInfo: false,
      bPaginate: false
    });
  });

app/views/admin/users/new.html.haml
= render partial: 'form'

app/views/admin/users/show.html.haml
.col-md-12
  .page-header
    %h1
      User #{@user.email}
      .btn-group.flex.pull-right.hidden-print
        = link_to edit_admin_user_path(@user), class: 'btn btn-primary' do
          .fas.fa-edit
        = link_to admin_user_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do
          .fas.fa-times

  %table.table.table-borderd.table-striped.table-hover#table-users
    %tbody
      %tr
        %th.col-md-2 ID
        %td= @user.id
      %tr
        %th Confirmed
        %td
          - if @user.confirmed?
            %label.btn-xs.btn-success.disabled
              Confirmed
          - else
            %label.btn-xs.btn-danger.disabled
              NOT Confirmed
            = link_to 'Confirm now', confirm_admin_user_path(@user), method: :patch, data: { confirm: "Are you sure you want to manually confirm this account for user #{@user.email}?" }, class: 'btn btn-xs btn-warning'
      %tr
        %th Name
        %td= @user.name
      %tr
        %th Created At
        %td= @user.created_at.in_time_zone('Athens')
      %tr
        %th Last sign in
        %td= @user.last_sign_in_at.in_time_zone('Athens') if @user.last_sign_in_at
      %tr
        %th Last sign in IP
        %td= @user.last_sign_in_ip